### PR TITLE
Bugfix/policy

### PR DESCRIPTION
**Pull request by w1lldone**
### Data Policy
- Any authenticated user can view and update data
- Any authenticated user can not create and delete data
- Admin can create, update, delete data

### Dashboard Policy
- Any authenticated user can view dashboard
- Any authenticated user can not create, update, delete dashboard
- Admin can view, create, update, delete dashboard

### User policy
- Any authenticated user can not view, update, delete, create user
- Admin can view, create, delete, update user

### Category Policy
- Any authenticated user can view categories
- Any authenticated user can not create, update, delete category
- User can create, view, update, delete category

## Additional changes
- Active filter indicator
image
- Fix welcome page layout
image
- Implement soft button on category, data, and user modals
image
- Remove required fields

### CODE REVIEW

**Comment by w1lldone** [comment]
@ebifurei @michaelr1300 Check this out. Habis ini saya akan bikin release 0.1.0 untuk di deploy di dashboard.bppugm.org

**Comment by ebifurei** [comment]
@w1lldone mas apakah Authenticated User tidak bisa melakukan filter by Assigned User ? 
image

**Comment by w1lldone** [comment]
> @w1lldone mas apakah Authenticated User tidak bisa melakukan filter by Assigned User ? image

Karena any authenticated user tidak boleh get all user, harusnya nggak boleh. Mungkin bisa ditambahi filter khusus any authenticated user "Assigned to me".

**Review by michaelr1300 — APPROVED** [review]
Sudah oke semua mas
Ada visual bug sedikit di bagian modal edit data, assigned user
Steps: 
- Login Any Authenticated User
- Edit data(1) yang sudah ada assigned user nya
- Close modal
- Edit data(2) yang belum ada assigned user nya
- Muncul nama user dari data(1) di modal edit data(2)


https://user-images.githubusercontent.com/46708593/193982223-042e0b9a-d6bd-46b1-8294-760a0397bd02.mp4

**Review by ebifurei — APPROVED** [review]

**Comment by w1lldone** [comment]
> Sudah oke semua mas Ada visual bug sedikit di bagian modal edit data, assigned user Steps:
> 
> * Login Any Authenticated User
> * Edit data(1) yang sudah ada assigned user nya
> * Close modal
> * Edit data(2) yang belum ada assigned user nya
> * Muncul nama user dari data(1) di modal edit data(2)
> 
>  Laravel.-.Google.Chrome.2022-10-05.11-33-42.mp4

Fixed 
Peek 2022-10-05 14-16

**Pull request merged**
